import type { Command } from "commander";
import { buildEdgeClaimsFromCurrentEdges } from "@supplystrata/claim-builder";
import { parseFormat, parseLimit, withDatabase, write, writeJson } from "../cli-utils.js";

export function registerClaimCommands(program: Command): void {
  const claims = program.command("claims").description("claim layer commands");

  claims
    .command("build")
    .option("--min-level <level>", "minimum evidence level, 4 or 5", "4")
    .option("--limit <count>", "max current edges to scan", "500")
    .option("--generated-by <id>", "builder id", "claim-builder.edge-fact.v1")
    .option("--format <format>", "markdown or json", "markdown")
    .description("build active claims from current non-inferred fact edges")
    .action(async (options: { minLevel: string; limit: string; generatedBy: string; format: string }) => {
      await withDatabase(async (pool) => {
        const summary = await buildEdgeClaimsFromCurrentEdges(pool, {
          min_evidence_level: parseMinEvidenceLevel(options.minLevel),
          limit: parseLimit(options.limit),
          generated_by: options.generatedBy
        });
        if (parseFormat(options.format) === "json") {
          writeJson({ ok: true, ...summary });
          return;
        }
        write(
          [
            "# Claim Build",
            "",
            `Generated by: ${summary.generated_by}`,
            `Scanned fact edges: ${summary.scanned}`,
            `Inserted claims: ${summary.inserted}`,
            `Updated claims: ${summary.updated}`
          ].join("\n")
        );
      });
    });
}

function parseMinEvidenceLevel(value: string): 4 | 5 {
  if (value === "4") return 4;
  if (value === "5") return 5;
  throw new Error(`Unsupported minimum evidence level: ${value}`);
}
