import type { SourceRegistryEntry } from "./types.js";

export const ENTITY_AND_FACILITY_SOURCES = [
  {
    id: "apple-suppliers",
    tier: "P0",
    name: "Apple Supplier List and Supply Chain Reports",
    category: "supplier_list",
    evidence_level_cap: 4,
    publisher_type: "official_supplier_list",
    relation_authority: "facility_claim",
    automation: "semi_auto",
    status: "preview",
    implemented_package: "@supplystrata/sources-apple-suppliers",
    requires_key: false,
    official_url: "https://www.apple.com/supplier-responsibility/",
    tos_url: "https://www.apple.com/legal/",
    notes: "官方 PDF；当前预览支持下载 FY22 Supplier List 并输出人工 review CSV，不自动 apply。"
  },
  {
    id: "opencorporates",
    tier: "P0",
    name: "OpenCorporates",
    category: "entity_resolution",
    evidence_level_cap: 4,
    publisher_type: "government_registry",
    relation_authority: "registry_fact",
    automation: "allowed",
    status: "preview",
    implemented_package: "@supplystrata/sources-opencorporates",
    requires_key: true,
    official_url: "https://api.opencorporates.com/documentation/API-Reference",
    tos_url: "https://opencorporates.com/info/licence",
    notes: "用于实体消歧；官方 API 当前要求 token，CLI lookup 只输出候选，不自动合并实体。"
  },
  {
    id: "companies-house",
    tier: "P0",
    name: "UK Companies House",
    category: "entity_resolution",
    evidence_level_cap: 4,
    publisher_type: "government_registry",
    relation_authority: "registry_fact",
    automation: "allowed",
    status: "preview",
    implemented_package: "@supplystrata/sources-companies-house",
    requires_key: true,
    official_url: "https://developer.company-information.service.gov.uk/",
    tos_url: "https://developer.company-information.service.gov.uk/",
    notes: "用于英国法人登记；官方 API key + Basic Auth，CLI lookup 只输出候选，不自动合并实体。"
  },
  {
    id: "gleif",
    tier: "P0",
    name: "GLEIF LEI Records",
    category: "entity_resolution",
    evidence_level_cap: 4,
    publisher_type: "government_registry",
    relation_authority: "registry_fact",
    automation: "allowed",
    status: "preview",
    implemented_package: "@supplystrata/source-workflows",
    requires_key: false,
    official_url: "https://www.gleif.org/en/lei-data/gleif-api",
    tos_url: "https://www.gleif.org/en/lei-data/lei-data-terms-of-use",
    notes: "全球 LEI 官方记录；作为跨 SEC / DART / EDINET / TWSE / HKEX 的实体标识锚点，lookup 只输出候选，不自动合并实体。"
  },
  {
    id: "seed-entities",
    tier: "P0",
    name: "Curated Seed Entities",
    category: "entity_resolution",
    evidence_level_cap: 4,
    publisher_type: "manual",
    relation_authority: "registry_fact",
    automation: "manual_only",
    status: "implemented",
    implemented_package: "@supplystrata/db",
    requires_key: false,
    official_url: "file://seeds/entities.csv",
    tos_url: "manual://curated-seeds",
    notes: "项目内维护的核心公司和高频供应商事实标识；只用于实体解析，不作为关系证据。"
  },
  {
    id: "rmi-facilities",
    tier: "P1",
    name: "Responsible Minerals Initiative Facility Lists",
    category: "facility",
    evidence_level_cap: 3,
    publisher_type: "official_supplier_list",
    relation_authority: "facility_claim",
    automation: "semi_auto",
    status: "scoped",
    requires_key: false,
    official_url: "https://www.responsiblemineralsinitiative.org/facilities-lists/",
    tos_url: "https://www.responsiblemineralsinitiative.org/",
    notes: "冶炼/精炼设施候选；必须和公司 responsible sourcing 报告交叉后才能升级。"
  },
  {
    id: "osh",
    tier: "P1",
    name: "Open Supply Hub",
    category: "facility",
    evidence_level_cap: 3,
    publisher_type: "official_supplier_list",
    relation_authority: "facility_claim",
    automation: "allowed",
    status: "preview",
    implemented_package: "@supplystrata/sources-osh",
    requires_key: true,
    official_url: "https://opensupplyhub.org/",
    tos_url: "https://info.opensupplyhub.org/terms-of-use",
    notes: "全球设施候选与 contributor 声明；需要 OSH API token；只写 FACILITY_PROFILE_OBSERVATION，与官方供应商名单交叉后才升级。"
  }
] as const satisfies readonly SourceRegistryEntry[];
