import type { SourceRegistryEntry } from "./types.js";

export const LEAD_AND_MANUAL_SOURCES = [
  {
    id: "sam-gov",
    tier: "P2",
    name: "SAM.gov Contract Opportunities",
    category: "procurement_news",
    evidence_level_cap: 2,
    publisher_type: "regulator",
    relation_authority: "lead_only",
    automation: "semi_auto",
    status: "scoped",
    requires_key: true,
    official_url: "https://sam.gov/content/opportunities",
    tos_url: "https://sam.gov/content/terms-of-use",
    notes: "美国联邦采购机会；默认进入 lead/hypothesis queue。"
  },
  {
    id: "usaspending",
    tier: "P2",
    name: "USAspending.gov",
    category: "procurement_news",
    evidence_level_cap: 2,
    publisher_type: "regulator",
    relation_authority: "lead_only",
    automation: "allowed",
    status: "scoped",
    requires_key: false,
    official_url: "https://api.usaspending.gov/",
    tos_url: "https://www.usaspending.gov/about",
    notes: "美国联邦合同/拨款；只能作为采购线索或需求侧 observation。"
  },
  {
    id: "eu-ted",
    tier: "P2",
    name: "EU TED",
    category: "procurement_news",
    evidence_level_cap: 2,
    publisher_type: "regulator",
    relation_authority: "lead_only",
    automation: "allowed",
    status: "scoped",
    requires_key: false,
    official_url: "https://ted.europa.eu/",
    tos_url: "https://ted.europa.eu/en/legal-notice",
    notes: "欧洲公共采购；默认进入 lead，不直接写供应链事实边。"
  },
  {
    id: "gdelt",
    tier: "P2",
    name: "GDELT",
    category: "procurement_news",
    evidence_level_cap: 1,
    publisher_type: "news",
    relation_authority: "lead_only",
    automation: "allowed",
    status: "scoped",
    requires_key: false,
    official_url: "https://www.gdeltproject.org/",
    tos_url: "https://www.gdeltproject.org/",
    notes: "新闻事件线索；只能进入 lead/hypothesis queue，不能直接升级事实边。"
  },
  {
    id: "manual",
    tier: "manual",
    name: "Manual Evidence",
    category: "manual",
    evidence_level_cap: 2,
    publisher_type: "manual",
    relation_authority: "lead_only",
    automation: "manual_only",
    status: "planned",
    requires_key: false,
    official_url: "manual://evidence",
    tos_url: "manual://evidence",
    notes: "人工录入本身不是原始来源；没有 underlying official source 时只能作为 lead，不能生成高等级事实边。"
  },
  {
    id: "import-yeti",
    tier: "manual",
    name: "ImportYeti",
    category: "trade",
    evidence_level_cap: 3,
    publisher_type: "manual",
    relation_authority: "lead_only",
    automation: "manual_only",
    status: "manual_only",
    requires_key: false,
    official_url: "https://www.importyeti.com/",
    tos_url: "https://www.importyeti.com/terms",
    notes: "不做 adapter，不自动抓取；仅允许研究员手工摘录少量证据。"
  }
] as const satisfies readonly SourceRegistryEntry[];
