import type { SourceRegistryEntry } from "./types.js";

export const OBSERVATION_SOURCES = [
  {
    id: "un-comtrade",
    tier: "P1",
    name: "UN Comtrade",
    category: "trade",
    evidence_level_cap: 2,
    publisher_type: "macro_statistical_agency",
    relation_authority: "macro_trend",
    automation: "allowed",
    status: "scoped",
    requires_key: true,
    official_url: "https://comtradeplus.un.org/",
    tos_url: "https://comtradeplus.un.org/",
    notes: "国家/商品贸易流；只能进入 observation，不能直接生成公司级供应链边。"
  },
  {
    id: "census-trade",
    tier: "P1",
    name: "U.S. Census International Trade",
    category: "trade",
    evidence_level_cap: 2,
    publisher_type: "macro_statistical_agency",
    relation_authority: "macro_trend",
    automation: "allowed",
    status: "preview",
    implemented_package: "@supplystrata/sources-census-trade",
    requires_key: true,
    official_url: "https://www.census.gov/data/developers/data-sets/international-trade.html",
    tos_url: "https://www.census.gov/data/developers/about/terms-of-service.html",
    notes: "美国进出口观测；需要免费 Census API key；只写 TRADE_FLOW_OBSERVATION，不证明公司-公司关系。"
  },
  {
    id: "usitc-dataweb",
    tier: "P1",
    name: "USITC DataWeb",
    category: "trade",
    evidence_level_cap: 2,
    publisher_type: "macro_statistical_agency",
    relation_authority: "macro_trend",
    automation: "semi_auto",
    status: "scoped",
    requires_key: false,
    official_url: "https://dataweb.usitc.gov/",
    tos_url: "https://www.usitc.gov/",
    notes: "美国官方贸易/关税数据；作为 trade observation，不直接入事实图。"
  },
  {
    id: "eia",
    tier: "P1",
    name: "U.S. Energy Information Administration",
    category: "macro",
    evidence_level_cap: 2,
    publisher_type: "macro_statistical_agency",
    relation_authority: "macro_trend",
    automation: "allowed",
    status: "scoped",
    requires_key: true,
    official_url: "https://www.eia.gov/opendata/",
    tos_url: "https://www.eia.gov/about/copyrights_reuse.php",
    notes: "能源和电力观测；用于工厂、数据中心、冶炼链背景，不生成供应链事实边。"
  },
  {
    id: "fred",
    tier: "P1",
    name: "FRED",
    category: "macro",
    evidence_level_cap: 2,
    publisher_type: "macro_statistical_agency",
    relation_authority: "macro_trend",
    automation: "allowed",
    status: "scoped",
    requires_key: true,
    official_url: "https://fred.stlouisfed.org/docs/api/fred/",
    tos_url: "https://fred.stlouisfed.org/docs/api/terms_of_use.html",
    notes: "宏观时间序列；只作为 observation 背景，不生成公司级边。"
  },
  {
    id: "worldbank-pink",
    tier: "P1",
    name: "World Bank Pink Sheet",
    category: "commodity",
    evidence_level_cap: 2,
    publisher_type: "macro_statistical_agency",
    relation_authority: "macro_trend",
    automation: "allowed",
    status: "preview",
    implemented_package: "@supplystrata/sources-worldbank-pink",
    requires_key: false,
    official_url: "https://www.worldbank.org/en/research/commodity-markets",
    tos_url: "https://www.worldbank.org/en/about/legal/terms-and-conditions",
    notes: "公开商品价格；作为 commodity observation，不证明公司采购关系。"
  },
  {
    id: "usgs-mcs",
    tier: "P1",
    name: "USGS Mineral Commodity Summaries",
    category: "commodity",
    evidence_level_cap: 2,
    publisher_type: "macro_statistical_agency",
    relation_authority: "macro_trend",
    automation: "semi_auto",
    status: "scoped",
    requires_key: false,
    official_url: "https://www.usgs.gov/centers/national-minerals-information-center/mineral-commodity-summaries",
    tos_url: "https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits",
    notes: "矿产产量、储量和主要国家；只进入 commodity/material observation。"
  },
  {
    id: "iea-critical-minerals",
    tier: "P1",
    name: "IEA Critical Minerals Data Explorer",
    category: "commodity",
    evidence_level_cap: 2,
    publisher_type: "macro_statistical_agency",
    relation_authority: "macro_trend",
    automation: "semi_auto",
    status: "scoped",
    requires_key: false,
    official_url: "https://www.iea.org/data-and-statistics/data-tools/critical-minerals-data-explorer",
    tos_url: "https://www.iea.org/terms",
    notes: "关键矿物供应/需求情景；只作长期材料约束 observation。"
  },
  {
    id: "eu-crma",
    tier: "P1",
    name: "EU Critical Raw Materials Act",
    category: "policy",
    evidence_level_cap: 2,
    publisher_type: "regulator",
    relation_authority: "macro_trend",
    automation: "semi_auto",
    status: "scoped",
    requires_key: false,
    official_url: "https://single-market-economy.ec.europa.eu/sectors/raw-materials/areas-specific-interest/critical-raw-materials_en",
    tos_url: "https://commission.europa.eu/legal-notice_en",
    notes: "关键原材料政策与风险背景；作为 policy observation，不生成公司级供应链边。"
  },
  {
    id: "ofac-sanctions",
    tier: "P0",
    name: "OFAC Sanctions List Service",
    category: "policy",
    evidence_level_cap: 4,
    publisher_type: "regulator",
    relation_authority: "macro_trend",
    automation: "allowed",
    status: "scoped",
    requires_key: false,
    official_url: "https://ofac.treasury.gov/sanctions-list-service",
    tos_url: "https://ofac.treasury.gov/useful-information",
    notes: "美国制裁清单；作为 policy constraint / alert context，不创建供应链事实边。"
  },
  {
    id: "bis-entity-list",
    tier: "P0",
    name: "BIS Entity List",
    category: "policy",
    evidence_level_cap: 4,
    publisher_type: "regulator",
    relation_authority: "macro_trend",
    automation: "allowed",
    status: "scoped",
    requires_key: false,
    official_url: "https://www.bis.gov/entity-list",
    tos_url: "https://www.bis.gov/",
    notes: "美国出口管制实体清单；作为 export-control constraint / alert context，不创建供应链事实边。"
  },
  {
    id: "eu-sanctions",
    tier: "P0",
    name: "EU Consolidated Sanctions List",
    category: "policy",
    evidence_level_cap: 4,
    publisher_type: "regulator",
    relation_authority: "macro_trend",
    automation: "allowed",
    status: "scoped",
    requires_key: false,
    official_url: "https://www.sanctionsmap.eu/",
    tos_url: "https://www.sanctionsmap.eu/",
    notes: "欧盟制裁清单；作为 policy constraint / alert context，不创建供应链事实边。"
  },
  {
    id: "noaa-ais",
    tier: "P2",
    name: "NOAA AccessAIS",
    category: "logistics",
    evidence_level_cap: 2,
    publisher_type: "macro_statistical_agency",
    relation_authority: "macro_trend",
    automation: "semi_auto",
    status: "scoped",
    requires_key: false,
    official_url: "https://coast.noaa.gov/digitalcoast/tools/ais.html",
    tos_url: "https://coast.noaa.gov/digitalcoast/tools/ais.html",
    notes: "船舶/港口活动背景；不能证明货物归属或公司级运输关系。"
  }
] as const satisfies readonly SourceRegistryEntry[];
