import type { SourceRegistryEntry } from "./types.js";

export const OFFICIAL_DISCLOSURE_SOURCES = [
  {
    id: "sec-edgar",
    tier: "P0",
    name: "SEC EDGAR",
    category: "official_disclosure",
    evidence_level_cap: 5,
    publisher_type: "regulator",
    relation_authority: "self_disclosure",
    automation: "allowed",
    status: "implemented",
    implemented_package: "@supplystrata/sources-sec-edgar",
    requires_key: false,
    official_url: "https://www.sec.gov/edgar/search-and-access",
    tos_url: "https://www.sec.gov/os/accessing-edgar-data",
    notes: "官方 API；必须带 User-Agent；当前支持 submissions + filing HTML。"
  },
  {
    id: "tsmc-ir",
    tier: "P0",
    name: "TSMC Investor Relations",
    category: "official_disclosure",
    evidence_level_cap: 4,
    publisher_type: "company_official",
    relation_authority: "self_disclosure",
    automation: "allowed",
    status: "preview",
    implemented_package: "@supplystrata/source-workflows",
    requires_key: false,
    official_url: "https://investor.tsmc.com/english/annual-reports",
    tos_url: "https://investor.tsmc.com/english/annual-reports",
    notes: "当前预览抓 2025 Annual Report HTML，用作 foundry/AI/HPC/advanced packaging 背景证据。"
  },
  {
    id: "samsung-ir",
    tier: "P0",
    name: "Samsung Electronics Investor Relations",
    category: "official_disclosure",
    evidence_level_cap: 4,
    publisher_type: "company_official",
    relation_authority: "self_disclosure",
    automation: "allowed",
    status: "preview",
    implemented_package: "@supplystrata/source-workflows",
    requires_key: false,
    official_url: "https://www.samsung.com/global/ir/",
    tos_url: "https://www.samsung.com/global/ir/",
    notes: "当前预览抓 2025 官方业绩披露/新闻稿，用于 Memory / Foundry 背景；Business Report PDF 留后续。"
  },
  {
    id: "skhynix-ir",
    tier: "P0",
    name: "SK hynix Investor Relations",
    category: "official_disclosure",
    evidence_level_cap: 4,
    publisher_type: "company_official",
    relation_authority: "self_disclosure",
    automation: "allowed",
    status: "preview",
    implemented_package: "@supplystrata/source-workflows",
    requires_key: false,
    official_url: "https://www.skhynix.com/eng/irMain.do",
    tos_url: "https://www.skhynix.com/eng/irMain.do",
    notes: "当前预览抓 2025 官方业绩披露/新闻页，用于 HBM/DRAM 供应侧背景；韩文/DART 留后续。"
  },
  {
    id: "micron-ir",
    tier: "P1",
    name: "Micron Investor Relations",
    category: "official_disclosure",
    evidence_level_cap: 4,
    publisher_type: "company_official",
    relation_authority: "self_disclosure",
    automation: "allowed",
    status: "preview",
    implemented_package: "@supplystrata/source-workflows",
    requires_key: false,
    official_url: "https://investors.micron.com/",
    tos_url: "https://www.micron.com/about/legal",
    notes: "当前预览抓 2025 IR SEC Filing Details 页面，用于 memory supplier filings 的官方背景；正文深度 parser 仍以后续 SEC/IR 规则为准。"
  },
  {
    id: "asml-ir",
    tier: "P0",
    name: "ASML Investor Relations",
    category: "official_disclosure",
    evidence_level_cap: 4,
    publisher_type: "company_official",
    relation_authority: "self_disclosure",
    automation: "allowed",
    status: "preview",
    implemented_package: "@supplystrata/source-workflows",
    requires_key: false,
    official_url: "https://www.asml.com/en/investors/annual-report",
    tos_url: "https://www.asml.com/en/investors/annual-report",
    notes: "当前预览抓 2025 Annual Report 页面，用于半导体设备链条背景。"
  },
  {
    id: "company-ir",
    tier: "P1",
    name: "Company Investor Relations",
    category: "official_disclosure",
    evidence_level_cap: 4,
    publisher_type: "company_official",
    relation_authority: "self_disclosure",
    automation: "semi_auto",
    status: "preview",
    implemented_package: "@supplystrata/source-workflows",
    requires_key: false,
    official_url: "manual://explicit-company-ir-url",
    tos_url: "manual://per-target-company-ir-tos",
    notes: "受控通用公司 IR HTML 入口；只有 target_config 明确提供已审阅 HTTPS URL、entity_id 和 year 时才可运行，不做自动发现、不猜任意公司页面。"
  },
  {
    id: "dart-kr",
    tier: "P1",
    name: "Korea DART",
    category: "official_disclosure",
    evidence_level_cap: 5,
    publisher_type: "regulator",
    relation_authority: "self_disclosure",
    automation: "allowed",
    status: "preview",
    implemented_package: "@supplystrata/source-workflows",
    requires_key: true,
    official_url: "https://opendart.fss.or.kr/",
    tos_url: "https://opendart.fss.or.kr/",
    notes: "韩国监管披露；当前先接 OpenDART disclosure list monitor，提供官方 target / source-check / readiness 覆盖。正文下载与韩文/HWP 解析仍留在后续阶段。"
  },
  {
    id: "edinet",
    tier: "P1",
    name: "Japan EDINET",
    category: "official_disclosure",
    evidence_level_cap: 5,
    publisher_type: "regulator",
    relation_authority: "self_disclosure",
    automation: "allowed",
    status: "preview",
    implemented_package: "@supplystrata/source-workflows",
    requires_key: true,
    official_url: "https://disclosure2.edinet-fsa.go.jp/",
    tos_url: "https://disclosure2.edinet-fsa.go.jp/",
    notes:
      "日本监管披露；当前先接 EDINET API v2 documents.json daily-filings monitor，提供官方 target / source-check / readiness 覆盖。正文 ZIP/PDF/XBRL 解析仍留后续。"
  },
  {
    id: "twse-mops",
    tier: "P1",
    name: "Taiwan MOPS",
    category: "official_disclosure",
    evidence_level_cap: 5,
    publisher_type: "regulator",
    relation_authority: "self_disclosure",
    automation: "semi_auto",
    status: "preview",
    implemented_package: "@supplystrata/source-workflows",
    requires_key: false,
    official_url: "https://mops.twse.com.tw/",
    tos_url: "https://mops.twse.com.tw/",
    notes: "台湾公开资讯观测站；当前先接电子文件查询目录 monitor，优先服务 Hon Hai / Quanta 等 AI server ODM 节点。PDF 正文解析与关系抽取留后续。"
  }
] as const satisfies readonly SourceRegistryEntry[];
